/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteReportsRouteImport } from './routes/route-reports'
import { Route as RouteImportTemplateRouteImport } from './routes/route-import-template'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehousesIndexRouteImport } from './routes/warehouses.index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as TransportRequestsIndexRouteImport } from './routes/transport-requests.index'
import { Route as SupplyIndexRouteImport } from './routes/supply.index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as DriversIndexRouteImport } from './routes/drivers.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DeliveryRoutesIndexRouteImport } from './routes/delivery-routes.index'
import { Route as CarriersIndexRouteImport } from './routes/carriers.index'
import { Route as WarehousesWarehouseIdRouteImport } from './routes/warehouses.$warehouseId'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as TransportRequestsRequestIdRouteImport } from './routes/transport-requests.$requestId'
import { Route as SupplyRequestsRouteImport } from './routes/supply.requests'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'
import { Route as DriverDeliveryRouteIdRouteImport } from './routes/driver.$deliveryRouteId'
import { Route as DeliveryRoutesDeliveryRouteIdRouteImport } from './routes/delivery-routes.$deliveryRouteId'
import { Route as CarriersVerificationRouteImport } from './routes/carriers.verification'
import { Route as CarriersCarrierIdRouteImport } from './routes/carriers.$carrierId'
import { Route as AdminTariffsRouteImport } from './routes/admin.tariffs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'

const RouteReportsRoute = RouteReportsRouteImport.update({
  id: '/route-reports',
  path: '/route-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteImportTemplateRoute = RouteImportTemplateRouteImport.update({
  id: '/route-import-template',
  path: '/route-import-template',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesIndexRoute = WarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRequestsIndexRoute = TransportRequestsIndexRouteImport.update({
  id: '/transport-requests/',
  path: '/transport-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyIndexRoute = SupplyIndexRouteImport.update({
  id: '/supply/',
  path: '/supply/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoutesIndexRoute = DeliveryRoutesIndexRouteImport.update({
  id: '/delivery-routes/',
  path: '/delivery-routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersIndexRoute = CarriersIndexRouteImport.update({
  id: '/carriers/',
  path: '/carriers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesWarehouseIdRoute = WarehousesWarehouseIdRouteImport.update({
  id: '/warehouses/$warehouseId',
  path: '/warehouses/$warehouseId',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRequestsRequestIdRoute =
  TransportRequestsRequestIdRouteImport.update({
    id: '/transport-requests/$requestId',
    path: '/transport-requests/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SupplyRequestsRoute = SupplyRequestsRouteImport.update({
  id: '/supply/requests',
  path: '/supply/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveryRouteIdRoute = DriverDeliveryRouteIdRouteImport.update({
  id: '/driver/$deliveryRouteId',
  path: '/driver/$deliveryRouteId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoutesDeliveryRouteIdRoute =
  DeliveryRoutesDeliveryRouteIdRouteImport.update({
    id: '/delivery-routes/$deliveryRouteId',
    path: '/delivery-routes/$deliveryRouteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CarriersVerificationRoute = CarriersVerificationRouteImport.update({
  id: '/carriers/verification',
  path: '/carriers/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersCarrierIdRoute = CarriersCarrierIdRouteImport.update({
  id: '/carriers/$carrierId',
  path: '/carriers/$carrierId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTariffsRoute = AdminTariffsRouteImport.update({
  id: '/admin/tariffs',
  path: '/admin/tariffs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/route-import-template': typeof RouteImportTemplateRoute
  '/route-reports': typeof RouteReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tariffs': typeof AdminTariffsRoute
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/carriers/verification': typeof CarriersVerificationRoute
  '/delivery-routes/$deliveryRouteId': typeof DeliveryRoutesDeliveryRouteIdRoute
  '/driver/$deliveryRouteId': typeof DriverDeliveryRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/supply/requests': typeof SupplyRequestsRoute
  '/transport-requests/$requestId': typeof TransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/carriers/': typeof CarriersIndexRoute
  '/delivery-routes/': typeof DeliveryRoutesIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/transport-requests/': typeof TransportRequestsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/route-import-template': typeof RouteImportTemplateRoute
  '/route-reports': typeof RouteReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tariffs': typeof AdminTariffsRoute
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/carriers/verification': typeof CarriersVerificationRoute
  '/delivery-routes/$deliveryRouteId': typeof DeliveryRoutesDeliveryRouteIdRoute
  '/driver/$deliveryRouteId': typeof DriverDeliveryRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/supply/requests': typeof SupplyRequestsRoute
  '/transport-requests/$requestId': typeof TransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/carriers': typeof CarriersIndexRoute
  '/delivery-routes': typeof DeliveryRoutesIndexRoute
  '/driver': typeof DriverIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/supply': typeof SupplyIndexRoute
  '/transport-requests': typeof TransportRequestsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/warehouses': typeof WarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/route-import-template': typeof RouteImportTemplateRoute
  '/route-reports': typeof RouteReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tariffs': typeof AdminTariffsRoute
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/carriers/verification': typeof CarriersVerificationRoute
  '/delivery-routes/$deliveryRouteId': typeof DeliveryRoutesDeliveryRouteIdRoute
  '/driver/$deliveryRouteId': typeof DriverDeliveryRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/supply/requests': typeof SupplyRequestsRoute
  '/transport-requests/$requestId': typeof TransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/carriers/': typeof CarriersIndexRoute
  '/delivery-routes/': typeof DeliveryRoutesIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/transport-requests/': typeof TransportRequestsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/route-import-template'
    | '/route-reports'
    | '/admin/settings'
    | '/admin/tariffs'
    | '/carriers/$carrierId'
    | '/carriers/verification'
    | '/delivery-routes/$deliveryRouteId'
    | '/driver/$deliveryRouteId'
    | '/routes/$routeId'
    | '/supply/requests'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
    | '/warehouses/$warehouseId'
    | '/carriers/'
    | '/delivery-routes/'
    | '/driver/'
    | '/drivers/'
    | '/routes/'
    | '/supply/'
    | '/transport-requests/'
    | '/vehicles/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/route-import-template'
    | '/route-reports'
    | '/admin/settings'
    | '/admin/tariffs'
    | '/carriers/$carrierId'
    | '/carriers/verification'
    | '/delivery-routes/$deliveryRouteId'
    | '/driver/$deliveryRouteId'
    | '/routes/$routeId'
    | '/supply/requests'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
    | '/warehouses/$warehouseId'
    | '/carriers'
    | '/delivery-routes'
    | '/driver'
    | '/drivers'
    | '/routes'
    | '/supply'
    | '/transport-requests'
    | '/vehicles'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/route-import-template'
    | '/route-reports'
    | '/admin/settings'
    | '/admin/tariffs'
    | '/carriers/$carrierId'
    | '/carriers/verification'
    | '/delivery-routes/$deliveryRouteId'
    | '/driver/$deliveryRouteId'
    | '/routes/$routeId'
    | '/supply/requests'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
    | '/warehouses/$warehouseId'
    | '/carriers/'
    | '/delivery-routes/'
    | '/driver/'
    | '/drivers/'
    | '/routes/'
    | '/supply/'
    | '/transport-requests/'
    | '/vehicles/'
    | '/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRoute
  RouteImportTemplateRoute: typeof RouteImportTemplateRoute
  RouteReportsRoute: typeof RouteReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTariffsRoute: typeof AdminTariffsRoute
  CarriersCarrierIdRoute: typeof CarriersCarrierIdRoute
  CarriersVerificationRoute: typeof CarriersVerificationRoute
  DeliveryRoutesDeliveryRouteIdRoute: typeof DeliveryRoutesDeliveryRouteIdRoute
  DriverDeliveryRouteIdRoute: typeof DriverDeliveryRouteIdRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  SupplyRequestsRoute: typeof SupplyRequestsRoute
  TransportRequestsRequestIdRoute: typeof TransportRequestsRequestIdRoute
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
  WarehousesWarehouseIdRoute: typeof WarehousesWarehouseIdRoute
  CarriersIndexRoute: typeof CarriersIndexRoute
  DeliveryRoutesIndexRoute: typeof DeliveryRoutesIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  SupplyIndexRoute: typeof SupplyIndexRoute
  TransportRequestsIndexRoute: typeof TransportRequestsIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  WarehousesIndexRoute: typeof WarehousesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/route-reports': {
      id: '/route-reports'
      path: '/route-reports'
      fullPath: '/route-reports'
      preLoaderRoute: typeof RouteReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-import-template': {
      id: '/route-import-template'
      path: '/route-import-template'
      fullPath: '/route-import-template'
      preLoaderRoute: typeof RouteImportTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/': {
      id: '/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof WarehousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-requests/': {
      id: '/transport-requests/'
      path: '/transport-requests'
      fullPath: '/transport-requests/'
      preLoaderRoute: typeof TransportRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/': {
      id: '/supply/'
      path: '/supply'
      fullPath: '/supply/'
      preLoaderRoute: typeof SupplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-routes/': {
      id: '/delivery-routes/'
      path: '/delivery-routes'
      fullPath: '/delivery-routes/'
      preLoaderRoute: typeof DeliveryRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers/': {
      id: '/carriers/'
      path: '/carriers'
      fullPath: '/carriers/'
      preLoaderRoute: typeof CarriersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/$warehouseId': {
      id: '/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof WarehousesWarehouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-requests/$requestId': {
      id: '/transport-requests/$requestId'
      path: '/transport-requests/$requestId'
      fullPath: '/transport-requests/$requestId'
      preLoaderRoute: typeof TransportRequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/requests': {
      id: '/supply/requests'
      path: '/supply/requests'
      fullPath: '/supply/requests'
      preLoaderRoute: typeof SupplyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/$deliveryRouteId': {
      id: '/driver/$deliveryRouteId'
      path: '/driver/$deliveryRouteId'
      fullPath: '/driver/$deliveryRouteId'
      preLoaderRoute: typeof DriverDeliveryRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-routes/$deliveryRouteId': {
      id: '/delivery-routes/$deliveryRouteId'
      path: '/delivery-routes/$deliveryRouteId'
      fullPath: '/delivery-routes/$deliveryRouteId'
      preLoaderRoute: typeof DeliveryRoutesDeliveryRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers/verification': {
      id: '/carriers/verification'
      path: '/carriers/verification'
      fullPath: '/carriers/verification'
      preLoaderRoute: typeof CarriersVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers/$carrierId': {
      id: '/carriers/$carrierId'
      path: '/carriers/$carrierId'
      fullPath: '/carriers/$carrierId'
      preLoaderRoute: typeof CarriersCarrierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tariffs': {
      id: '/admin/tariffs'
      path: '/admin/tariffs'
      fullPath: '/admin/tariffs'
      preLoaderRoute: typeof AdminTariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRoute,
  RouteImportTemplateRoute: RouteImportTemplateRoute,
  RouteReportsRoute: RouteReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTariffsRoute: AdminTariffsRoute,
  CarriersCarrierIdRoute: CarriersCarrierIdRoute,
  CarriersVerificationRoute: CarriersVerificationRoute,
  DeliveryRoutesDeliveryRouteIdRoute: DeliveryRoutesDeliveryRouteIdRoute,
  DriverDeliveryRouteIdRoute: DriverDeliveryRouteIdRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  SupplyRequestsRoute: SupplyRequestsRoute,
  TransportRequestsRequestIdRoute: TransportRequestsRequestIdRoute,
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
  WarehousesWarehouseIdRoute: WarehousesWarehouseIdRoute,
  CarriersIndexRoute: CarriersIndexRoute,
  DeliveryRoutesIndexRoute: DeliveryRoutesIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  SupplyIndexRoute: SupplyIndexRoute,
  TransportRequestsIndexRoute: TransportRequestsIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  WarehousesIndexRoute: WarehousesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
