/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WarehouseTodayRouteImport } from './routes/warehouse-today'
import { Route as WarehouseStockRouteImport } from './routes/warehouse-stock'
import { Route as WarehouseSettingsRouteImport } from './routes/warehouse-settings'
import { Route as WarehouseScheduleRouteImport } from './routes/warehouse-schedule'
import { Route as WarehouseReturnsRouteImport } from './routes/warehouse-returns'
import { Route as WarehouseReportRouteImport } from './routes/warehouse-report'
import { Route as WarehouseInboundRouteImport } from './routes/warehouse-inbound'
import { Route as SystemTestRouteImport } from './routes/system-test'
import { Route as SystemIssuesRouteImport } from './routes/system-issues'
import { Route as RouteReportsRouteImport } from './routes/route-reports'
import { Route as RouteImportTemplateRouteImport } from './routes/route-import-template'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LogistRouteImport } from './routes/logist'
import { Route as FirstRunRouteImport } from './routes/first-run'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehousesIndexRouteImport } from './routes/warehouses.index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as TransportRequestsIndexRouteImport } from './routes/transport-requests.index'
import { Route as SupplyIndexRouteImport } from './routes/supply.index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as DriversIndexRouteImport } from './routes/drivers.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DeliveryRoutesIndexRouteImport } from './routes/delivery-routes.index'
import { Route as CarriersIndexRouteImport } from './routes/carriers.index'
import { Route as WarehousesWarehouseIdRouteImport } from './routes/warehouses.$warehouseId'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as TransportRequestsRequestIdRouteImport } from './routes/transport-requests.$requestId'
import { Route as SupplyRequestsRouteImport } from './routes/supply.requests'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'
import { Route as DriverDeliveryRouteIdRouteImport } from './routes/driver.$deliveryRouteId'
import { Route as DeliveryRoutesDeliveryRouteIdRouteImport } from './routes/delivery-routes.$deliveryRouteId'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as CarriersVerificationRouteImport } from './routes/carriers.verification'
import { Route as CarriersCarrierIdRouteImport } from './routes/carriers.$carrierId'
import { Route as AdminTariffsRouteImport } from './routes/admin.tariffs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseTodayRoute = WarehouseTodayRouteImport.update({
  id: '/warehouse-today',
  path: '/warehouse-today',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseStockRoute = WarehouseStockRouteImport.update({
  id: '/warehouse-stock',
  path: '/warehouse-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseSettingsRoute = WarehouseSettingsRouteImport.update({
  id: '/warehouse-settings',
  path: '/warehouse-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseScheduleRoute = WarehouseScheduleRouteImport.update({
  id: '/warehouse-schedule',
  path: '/warehouse-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseReturnsRoute = WarehouseReturnsRouteImport.update({
  id: '/warehouse-returns',
  path: '/warehouse-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseReportRoute = WarehouseReportRouteImport.update({
  id: '/warehouse-report',
  path: '/warehouse-report',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseInboundRoute = WarehouseInboundRouteImport.update({
  id: '/warehouse-inbound',
  path: '/warehouse-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemTestRoute = SystemTestRouteImport.update({
  id: '/system-test',
  path: '/system-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIssuesRoute = SystemIssuesRouteImport.update({
  id: '/system-issues',
  path: '/system-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteReportsRoute = RouteReportsRouteImport.update({
  id: '/route-reports',
  path: '/route-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteImportTemplateRoute = RouteImportTemplateRouteImport.update({
  id: '/route-import-template',
  path: '/route-import-template',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LogistRoute = LogistRouteImport.update({
  id: '/logist',
  path: '/logist',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstRunRoute = FirstRunRouteImport.update({
  id: '/first-run',
  path: '/first-run',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesIndexRoute = WarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRequestsIndexRoute = TransportRequestsIndexRouteImport.update({
  id: '/transport-requests/',
  path: '/transport-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyIndexRoute = SupplyIndexRouteImport.update({
  id: '/supply/',
  path: '/supply/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoutesIndexRoute = DeliveryRoutesIndexRouteImport.update({
  id: '/delivery-routes/',
  path: '/delivery-routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersIndexRoute = CarriersIndexRouteImport.update({
  id: '/carriers/',
  path: '/carriers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesWarehouseIdRoute = WarehousesWarehouseIdRouteImport.update({
  id: '/warehouses/$warehouseId',
  path: '/warehouses/$warehouseId',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRequestsRequestIdRoute =
  TransportRequestsRequestIdRouteImport.update({
    id: '/transport-requests/$requestId',
    path: '/transport-requests/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SupplyRequestsRoute = SupplyRequestsRouteImport.update({
  id: '/supply/requests',
  path: '/supply/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveryRouteIdRoute = DriverDeliveryRouteIdRouteImport.update({
  id: '/driver/$deliveryRouteId',
  path: '/driver/$deliveryRouteId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoutesDeliveryRouteIdRoute =
  DeliveryRoutesDeliveryRouteIdRouteImport.update({
    id: '/delivery-routes/$deliveryRouteId',
    path: '/delivery-routes/$deliveryRouteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersVerificationRoute = CarriersVerificationRouteImport.update({
  id: '/carriers/verification',
  path: '/carriers/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersCarrierIdRoute = CarriersCarrierIdRouteImport.update({
  id: '/carriers/$carrierId',
  path: '/carriers/$carrierId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTariffsRoute = AdminTariffsRouteImport.update({
  id: '/admin/tariffs',
  path: '/admin/tariffs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/first-run': typeof FirstRunRoute
  '/logist': typeof LogistRoute
  '/notifications': typeof NotificationsRoute
  '/route-import-template': typeof RouteImportTemplateRoute
  '/route-reports': typeof RouteReportsRoute
  '/system-issues': typeof SystemIssuesRoute
  '/system-test': typeof SystemTestRoute
  '/warehouse-inbound': typeof WarehouseInboundRoute
  '/warehouse-report': typeof WarehouseReportRoute
  '/warehouse-returns': typeof WarehouseReturnsRoute
  '/warehouse-schedule': typeof WarehouseScheduleRoute
  '/warehouse-settings': typeof WarehouseSettingsRoute
  '/warehouse-stock': typeof WarehouseStockRoute
  '/warehouse-today': typeof WarehouseTodayRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tariffs': typeof AdminTariffsRoute
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/carriers/verification': typeof CarriersVerificationRoute
  '/d/$token': typeof DTokenRoute
  '/delivery-routes/$deliveryRouteId': typeof DeliveryRoutesDeliveryRouteIdRoute
  '/driver/$deliveryRouteId': typeof DriverDeliveryRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/supply/requests': typeof SupplyRequestsRoute
  '/transport-requests/$requestId': typeof TransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/carriers/': typeof CarriersIndexRoute
  '/delivery-routes/': typeof DeliveryRoutesIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/transport-requests/': typeof TransportRequestsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/first-run': typeof FirstRunRoute
  '/logist': typeof LogistRoute
  '/notifications': typeof NotificationsRoute
  '/route-import-template': typeof RouteImportTemplateRoute
  '/route-reports': typeof RouteReportsRoute
  '/system-issues': typeof SystemIssuesRoute
  '/system-test': typeof SystemTestRoute
  '/warehouse-inbound': typeof WarehouseInboundRoute
  '/warehouse-report': typeof WarehouseReportRoute
  '/warehouse-returns': typeof WarehouseReturnsRoute
  '/warehouse-schedule': typeof WarehouseScheduleRoute
  '/warehouse-settings': typeof WarehouseSettingsRoute
  '/warehouse-stock': typeof WarehouseStockRoute
  '/warehouse-today': typeof WarehouseTodayRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tariffs': typeof AdminTariffsRoute
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/carriers/verification': typeof CarriersVerificationRoute
  '/d/$token': typeof DTokenRoute
  '/delivery-routes/$deliveryRouteId': typeof DeliveryRoutesDeliveryRouteIdRoute
  '/driver/$deliveryRouteId': typeof DriverDeliveryRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/supply/requests': typeof SupplyRequestsRoute
  '/transport-requests/$requestId': typeof TransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/carriers': typeof CarriersIndexRoute
  '/delivery-routes': typeof DeliveryRoutesIndexRoute
  '/driver': typeof DriverIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/supply': typeof SupplyIndexRoute
  '/transport-requests': typeof TransportRequestsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/warehouses': typeof WarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/first-run': typeof FirstRunRoute
  '/logist': typeof LogistRoute
  '/notifications': typeof NotificationsRoute
  '/route-import-template': typeof RouteImportTemplateRoute
  '/route-reports': typeof RouteReportsRoute
  '/system-issues': typeof SystemIssuesRoute
  '/system-test': typeof SystemTestRoute
  '/warehouse-inbound': typeof WarehouseInboundRoute
  '/warehouse-report': typeof WarehouseReportRoute
  '/warehouse-returns': typeof WarehouseReturnsRoute
  '/warehouse-schedule': typeof WarehouseScheduleRoute
  '/warehouse-settings': typeof WarehouseSettingsRoute
  '/warehouse-stock': typeof WarehouseStockRoute
  '/warehouse-today': typeof WarehouseTodayRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tariffs': typeof AdminTariffsRoute
  '/carriers/$carrierId': typeof CarriersCarrierIdRoute
  '/carriers/verification': typeof CarriersVerificationRoute
  '/d/$token': typeof DTokenRoute
  '/delivery-routes/$deliveryRouteId': typeof DeliveryRoutesDeliveryRouteIdRoute
  '/driver/$deliveryRouteId': typeof DriverDeliveryRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/supply/requests': typeof SupplyRequestsRoute
  '/transport-requests/$requestId': typeof TransportRequestsRequestIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/carriers/': typeof CarriersIndexRoute
  '/delivery-routes/': typeof DeliveryRoutesIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/supply/': typeof SupplyIndexRoute
  '/transport-requests/': typeof TransportRequestsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/director'
    | '/first-run'
    | '/logist'
    | '/notifications'
    | '/route-import-template'
    | '/route-reports'
    | '/system-issues'
    | '/system-test'
    | '/warehouse-inbound'
    | '/warehouse-report'
    | '/warehouse-returns'
    | '/warehouse-schedule'
    | '/warehouse-settings'
    | '/warehouse-stock'
    | '/warehouse-today'
    | '/workspace'
    | '/admin/settings'
    | '/admin/tariffs'
    | '/carriers/$carrierId'
    | '/carriers/verification'
    | '/d/$token'
    | '/delivery-routes/$deliveryRouteId'
    | '/driver/$deliveryRouteId'
    | '/routes/$routeId'
    | '/supply/requests'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
    | '/warehouses/$warehouseId'
    | '/carriers/'
    | '/delivery-routes/'
    | '/driver/'
    | '/drivers/'
    | '/routes/'
    | '/supply/'
    | '/transport-requests/'
    | '/vehicles/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/director'
    | '/first-run'
    | '/logist'
    | '/notifications'
    | '/route-import-template'
    | '/route-reports'
    | '/system-issues'
    | '/system-test'
    | '/warehouse-inbound'
    | '/warehouse-report'
    | '/warehouse-returns'
    | '/warehouse-schedule'
    | '/warehouse-settings'
    | '/warehouse-stock'
    | '/warehouse-today'
    | '/workspace'
    | '/admin/settings'
    | '/admin/tariffs'
    | '/carriers/$carrierId'
    | '/carriers/verification'
    | '/d/$token'
    | '/delivery-routes/$deliveryRouteId'
    | '/driver/$deliveryRouteId'
    | '/routes/$routeId'
    | '/supply/requests'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
    | '/warehouses/$warehouseId'
    | '/carriers'
    | '/delivery-routes'
    | '/driver'
    | '/drivers'
    | '/routes'
    | '/supply'
    | '/transport-requests'
    | '/vehicles'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/director'
    | '/first-run'
    | '/logist'
    | '/notifications'
    | '/route-import-template'
    | '/route-reports'
    | '/system-issues'
    | '/system-test'
    | '/warehouse-inbound'
    | '/warehouse-report'
    | '/warehouse-returns'
    | '/warehouse-schedule'
    | '/warehouse-settings'
    | '/warehouse-stock'
    | '/warehouse-today'
    | '/workspace'
    | '/admin/settings'
    | '/admin/tariffs'
    | '/carriers/$carrierId'
    | '/carriers/verification'
    | '/d/$token'
    | '/delivery-routes/$deliveryRouteId'
    | '/driver/$deliveryRouteId'
    | '/routes/$routeId'
    | '/supply/requests'
    | '/transport-requests/$requestId'
    | '/vehicles/$vehicleId'
    | '/warehouses/$warehouseId'
    | '/carriers/'
    | '/delivery-routes/'
    | '/driver/'
    | '/drivers/'
    | '/routes/'
    | '/supply/'
    | '/transport-requests/'
    | '/vehicles/'
    | '/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectorRoute: typeof DirectorRoute
  FirstRunRoute: typeof FirstRunRoute
  LogistRoute: typeof LogistRoute
  NotificationsRoute: typeof NotificationsRoute
  RouteImportTemplateRoute: typeof RouteImportTemplateRoute
  RouteReportsRoute: typeof RouteReportsRoute
  SystemIssuesRoute: typeof SystemIssuesRoute
  SystemTestRoute: typeof SystemTestRoute
  WarehouseInboundRoute: typeof WarehouseInboundRoute
  WarehouseReportRoute: typeof WarehouseReportRoute
  WarehouseReturnsRoute: typeof WarehouseReturnsRoute
  WarehouseScheduleRoute: typeof WarehouseScheduleRoute
  WarehouseSettingsRoute: typeof WarehouseSettingsRoute
  WarehouseStockRoute: typeof WarehouseStockRoute
  WarehouseTodayRoute: typeof WarehouseTodayRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTariffsRoute: typeof AdminTariffsRoute
  CarriersCarrierIdRoute: typeof CarriersCarrierIdRoute
  CarriersVerificationRoute: typeof CarriersVerificationRoute
  DTokenRoute: typeof DTokenRoute
  DeliveryRoutesDeliveryRouteIdRoute: typeof DeliveryRoutesDeliveryRouteIdRoute
  DriverDeliveryRouteIdRoute: typeof DriverDeliveryRouteIdRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  SupplyRequestsRoute: typeof SupplyRequestsRoute
  TransportRequestsRequestIdRoute: typeof TransportRequestsRequestIdRoute
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
  WarehousesWarehouseIdRoute: typeof WarehousesWarehouseIdRoute
  CarriersIndexRoute: typeof CarriersIndexRoute
  DeliveryRoutesIndexRoute: typeof DeliveryRoutesIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  SupplyIndexRoute: typeof SupplyIndexRoute
  TransportRequestsIndexRoute: typeof TransportRequestsIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  WarehousesIndexRoute: typeof WarehousesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-today': {
      id: '/warehouse-today'
      path: '/warehouse-today'
      fullPath: '/warehouse-today'
      preLoaderRoute: typeof WarehouseTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-stock': {
      id: '/warehouse-stock'
      path: '/warehouse-stock'
      fullPath: '/warehouse-stock'
      preLoaderRoute: typeof WarehouseStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-settings': {
      id: '/warehouse-settings'
      path: '/warehouse-settings'
      fullPath: '/warehouse-settings'
      preLoaderRoute: typeof WarehouseSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-schedule': {
      id: '/warehouse-schedule'
      path: '/warehouse-schedule'
      fullPath: '/warehouse-schedule'
      preLoaderRoute: typeof WarehouseScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-returns': {
      id: '/warehouse-returns'
      path: '/warehouse-returns'
      fullPath: '/warehouse-returns'
      preLoaderRoute: typeof WarehouseReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-report': {
      id: '/warehouse-report'
      path: '/warehouse-report'
      fullPath: '/warehouse-report'
      preLoaderRoute: typeof WarehouseReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-inbound': {
      id: '/warehouse-inbound'
      path: '/warehouse-inbound'
      fullPath: '/warehouse-inbound'
      preLoaderRoute: typeof WarehouseInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-test': {
      id: '/system-test'
      path: '/system-test'
      fullPath: '/system-test'
      preLoaderRoute: typeof SystemTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-issues': {
      id: '/system-issues'
      path: '/system-issues'
      fullPath: '/system-issues'
      preLoaderRoute: typeof SystemIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-reports': {
      id: '/route-reports'
      path: '/route-reports'
      fullPath: '/route-reports'
      preLoaderRoute: typeof RouteReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-import-template': {
      id: '/route-import-template'
      path: '/route-import-template'
      fullPath: '/route-import-template'
      preLoaderRoute: typeof RouteImportTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logist': {
      id: '/logist'
      path: '/logist'
      fullPath: '/logist'
      preLoaderRoute: typeof LogistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-run': {
      id: '/first-run'
      path: '/first-run'
      fullPath: '/first-run'
      preLoaderRoute: typeof FirstRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/': {
      id: '/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof WarehousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-requests/': {
      id: '/transport-requests/'
      path: '/transport-requests'
      fullPath: '/transport-requests/'
      preLoaderRoute: typeof TransportRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/': {
      id: '/supply/'
      path: '/supply'
      fullPath: '/supply/'
      preLoaderRoute: typeof SupplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-routes/': {
      id: '/delivery-routes/'
      path: '/delivery-routes'
      fullPath: '/delivery-routes/'
      preLoaderRoute: typeof DeliveryRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers/': {
      id: '/carriers/'
      path: '/carriers'
      fullPath: '/carriers/'
      preLoaderRoute: typeof CarriersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/$warehouseId': {
      id: '/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof WarehousesWarehouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-requests/$requestId': {
      id: '/transport-requests/$requestId'
      path: '/transport-requests/$requestId'
      fullPath: '/transport-requests/$requestId'
      preLoaderRoute: typeof TransportRequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply/requests': {
      id: '/supply/requests'
      path: '/supply/requests'
      fullPath: '/supply/requests'
      preLoaderRoute: typeof SupplyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/$deliveryRouteId': {
      id: '/driver/$deliveryRouteId'
      path: '/driver/$deliveryRouteId'
      fullPath: '/driver/$deliveryRouteId'
      preLoaderRoute: typeof DriverDeliveryRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-routes/$deliveryRouteId': {
      id: '/delivery-routes/$deliveryRouteId'
      path: '/delivery-routes/$deliveryRouteId'
      fullPath: '/delivery-routes/$deliveryRouteId'
      preLoaderRoute: typeof DeliveryRoutesDeliveryRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers/verification': {
      id: '/carriers/verification'
      path: '/carriers/verification'
      fullPath: '/carriers/verification'
      preLoaderRoute: typeof CarriersVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers/$carrierId': {
      id: '/carriers/$carrierId'
      path: '/carriers/$carrierId'
      fullPath: '/carriers/$carrierId'
      preLoaderRoute: typeof CarriersCarrierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tariffs': {
      id: '/admin/tariffs'
      path: '/admin/tariffs'
      fullPath: '/admin/tariffs'
      preLoaderRoute: typeof AdminTariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectorRoute: DirectorRoute,
  FirstRunRoute: FirstRunRoute,
  LogistRoute: LogistRoute,
  NotificationsRoute: NotificationsRoute,
  RouteImportTemplateRoute: RouteImportTemplateRoute,
  RouteReportsRoute: RouteReportsRoute,
  SystemIssuesRoute: SystemIssuesRoute,
  SystemTestRoute: SystemTestRoute,
  WarehouseInboundRoute: WarehouseInboundRoute,
  WarehouseReportRoute: WarehouseReportRoute,
  WarehouseReturnsRoute: WarehouseReturnsRoute,
  WarehouseScheduleRoute: WarehouseScheduleRoute,
  WarehouseSettingsRoute: WarehouseSettingsRoute,
  WarehouseStockRoute: WarehouseStockRoute,
  WarehouseTodayRoute: WarehouseTodayRoute,
  WorkspaceRoute: WorkspaceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTariffsRoute: AdminTariffsRoute,
  CarriersCarrierIdRoute: CarriersCarrierIdRoute,
  CarriersVerificationRoute: CarriersVerificationRoute,
  DTokenRoute: DTokenRoute,
  DeliveryRoutesDeliveryRouteIdRoute: DeliveryRoutesDeliveryRouteIdRoute,
  DriverDeliveryRouteIdRoute: DriverDeliveryRouteIdRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  SupplyRequestsRoute: SupplyRequestsRoute,
  TransportRequestsRequestIdRoute: TransportRequestsRequestIdRoute,
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
  WarehousesWarehouseIdRoute: WarehousesWarehouseIdRoute,
  CarriersIndexRoute: CarriersIndexRoute,
  DeliveryRoutesIndexRoute: DeliveryRoutesIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  SupplyIndexRoute: SupplyIndexRoute,
  TransportRequestsIndexRoute: TransportRequestsIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  WarehousesIndexRoute: WarehousesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
